version: 2
updates:
  - package-ecosystem: "pip" # Use pip as the ecosystem for Poetry projects
    directory: "/" # Path to your project root where pyproject.toml is located
    schedule:
      interval: "daily" # Check for updates daily
    versioning-strategy: "increase-if-necessary" # Update to the latest version if necessary
    ignore:
      - dependency-name: "python" # Optional: Ignore updates to Python itself
    commit-message:
      prefix: "deps" # Customize the commit message prefix for PRs