name: Update Python Poetry packages

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: Apakottur/action-poetry-package-update@v1
        with:
          python-version: 3.11
          poetry-version: 2.1.0
          base-branch: main
